### ISSUE TITLE
Why not drop HTTPie dependency in favor of curl?

### ISSUE THREAD

**Issue by specious** [hanksudo/npm-package-info#1]
I know that [HTTPie](https://httpie.org) is an amazing utility, but since it's only being used to [fetch the package manifest file](https://github.com/hanksudo/npm-package-info/blob/202f4b93351572dae8d83a4fbebcc8dc81d01d1b/npi.sh#L20), I would consider dropping the dependency and instead use [curl](https://github.com/curl/curl) which is more ubiquitous.

**Comment by hanksudo** [comment]
Yes, you are right, I drop the HTTPie instead use curl now. thanks.
